---
title: "Task 8"
output:
  html_document:  
    keep_md: true
  html_notebook: default
---

##Introduction:
The following code was written in completion of Task08. The purpose of this task was to learn how to write functions. 

##Function 1

###Functions and error handling: 
The goal was to write a function that fulfills the following criteria:
  It should be tidyverse compatible (i.e., the first argument must be a data frame)
  It should add two arbitrary columns of the data frame (specified by the user) and put them in a new column of that data frame, with the name of the new column specified by the user
  
Error messages should also be included:
It should throw an informative warning if any invalid arguments are provided.   Invalid arguments might include:
  The first argument is not a data frame
  Less than two valid columns are specified to add (e.g., one or both of the column names isn't in the supplied data frame)
  The columns specified are not numeric, and therefore can't be added - use tryCatch() for this
  If the columns to add aren't valid but the new column name is, the function should create a column of NA values

```{r}
#using the nycflights/weather dataset, which is a tibble data set.
x<- nycflights13::weather

#This function takes 4 arguments, the first being the dataframe and the last three as columns
col_add <- function(df, i, j, k){ 
  
#This sets the warning if the first argument is not a data frame.
  if(is.data.frame(df) != TRUE) stop("The first argument is not a data frame") 

#This creates a warning if the column specified does not belong to the dataframe used in the function
  if(is.data.frame(df[[i]]) != TRUE | is.data.frame(df[[j]]) !=TRUE) warning("i or j does not belong to df")

#sums columns i and j and creates a new column "k", which can be named when the function is called  
  df[[k]] <- (df[[i]] + df[[j]]) 
  
#use trycatch() if the columns to add aren't valid but the new column name is, the function should create a column of NA values
#tryCatch(is.data.frame(), error=function(cond) FALSE) #Not sure how to use trycatch()

#returns the original data frame.
  return(df) 
}

#Calling the function
col_add(x, "humid", "precip", "mynewcol") 

```


